# Generated by Django 5.1.7 on 2025-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAsked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60, verbose_name='Pytanie')),
                ('answer', models.TextField(verbose_name='Odpowiedź')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Najczęściej zadawane pytania',
            },
        ),
        migrations.CreateModel(
            name='MessagesFromForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Imię')),
                ('subject', models.CharField(max_length=60, verbose_name='Temat')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Wysłano')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
            },
        ),
        migrations.CreateModel(
            name='ProjectsDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa projektu')),
                ('description', models.TextField(verbose_name='Opis projektu')),
                ('image', models.ImageField(upload_to='projects_done/', verbose_name='Zdjęcie projektu')),
            ],
            options={
                'verbose_name': 'Zakończony projekt',
                'verbose_name_plural': 'Zakończone projekty',
            },
        ),
        migrations.CreateModel(
            name='ServiceOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa usługi')),
                ('description', models.TextField(verbose_name='Opis usługi')),
                ('image', models.ImageField(upload_to='service_offers/')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
            },
        ),
    ]
