# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffers',
            name='image',
        ),
    ]
