# Generated by Django 5.1.7 on 2025-03-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_remove_serviceoffers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsdone',
            name='image',
            field=models.ImageField(null=True, upload_to='projects_done/', verbose_name='Zdjęcie projektu'),
        ),
    ]
